;;; set prefix
(set-prefix-key (kbd "C-t"))

;;; set keys
(define-key *root-map* (kbd "c") "exec st")
(define-key *root-map* (kbd "C-c") "exec st")
(define-key *root-map* (kbd "C-q") "exec slock")
(define-key *root-map* (kbd "C-f") "fullscreen")
(define-key *root-map* (kbd "C--") "toggle-gaps")
(define-key *root-map* (kbd "q") "end-session")
(define-key *root-map* (kbd "C-+") "float-this")
(define-key *root-map* (kbd "*") "unfloat-this")
(define-key *root-map* (kbd "C-s") "swm-ssh-menu")
; (define-key *root-map* (kbd "C-v") "swm-vpn")
(define-key *root-map* (kbd "C-v") "vpn-connect")
(define-key *root-map* (kbd "C-d") "vpn-disconnect")
(define-key *root-map* (kbd "C-_") "mode-line")
(define-key *root-map* (kbd "C-b") "brave")
(define-key *root-map* (kbd "b") "brave")
(define-key *top-map* (kbd "M-p") "show-menu")
