#!/usr/bin/env bash

sxhkd -c $HOME/.config/berry/sxhkdrc &
# $HOME/.config/berry/bar &

# Set decoration geometry
berryc border_width       5
berryc inner_border_width 3
berryc title_height       30
berryc top_gap            0

# Set decoration colors
berryc focus_color         000000
berryc unfocus_color       292D3E
berryc inner_focus_color   000000
berryc inner_unfocus_color 292D3E
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "CascadiaCode Nerd Font:size=18"

